name: Build

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: '0.6.2'

      - name: Install dependencies
        run: uv sync

      - name: Run ruff
        run: uv run ruff check llama_index

      - name: Run mypy
        run: |
          export MYPYPATH=${{ github.workspace }}/llama_index
          uv run mypy llama_index --namespace-packages --explicit-package-bases --disallow-untyped-defs --ignore-missing-imports --python-version=3.9

      - name: Run Tests
        run: uv run pytest
